services:
  service:
    image: ghcr.io/cloudsftp/solarminer-service:latest
    volumes:
      - .env:/.env

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "6681:5432"
    volumes:
      - ~/timescaledb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  nats:
    image: nats:latest
    ports:
      - "6682:4222" # Client connections
      - "6683:6222" # Routes
      - "6684:8222" # Monitoring
    command: "--name main --jetstream --http_port 8222 --tls --tlscert /cert.pem --tlskey /key.pem"
    volumes:
      - ~/jetstream-data:/tmp/nats/jetstream
      - /etc/letsencrypt/live/solarminer.energiesandsuch.com/fullchain.pem:/cert.pem
      - /etc/letsencrypt/live/solarminer.energiesandsuch.com/privkey.pem:/key.pem
    healthcheck:
      test: ["CMD-SHELL", "nats-server --version"]
      interval: 30s
      timeout: 10s
      retries: 3
