services:
  service:
    image: ghcr.io/cloudsftp/solarminer-service:latest
    volumes:
      - .env:/.env
    depends_on:
      nats:
        condition: service_started
      timescaledb:
        condition: service_healthy
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "6681:5432"
    volumes:
      - ~/timescaledb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${TIMESCALEDB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  nats:
    image: nats:latest
    ports:
      - "6682:4222" # Client connections
      - "6683:6222" # Routes
      - "6684:8222" # Monitoring
    command: "-c /nats.conf --auth ${NATS_TOKEN}"
    volumes:
      - ~/jetstream-data:/tmp/nats/jetstream
      - /etc/letsencrypt/live/solarminer.energiesandsuch.com-0003/fullchain.pem:/cert.pem
      - /etc/letsencrypt/live/solarminer.energiesandsuch.com-0003/privkey.pem:/key.pem
      - ./nats.conf:/nats.conf
    restart: unless-stopped
